name: "homeassistant-acme"
description: "A docker container to renew cert with acme and godaddy"
version: "1.17.0"
slug: "homeassistant-acme"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
options:
  acme_email: ''
  acme_gd_key: ''
  acme_gd_secret: ''
  acme_cf_zone_id: ''
  acme_cf_token: ''
  acme_dns_provider: ''
  acme_domain: ''
  acme_issuer: zerossl
schema:
  acme_email: str
  acme_gd_key: password
  acme_gd_secret: password
  acme_cf_token: password
  acme_cf_zone_id: str
  acme_dns_provder: str
  acme_domain: str
  acme_issuer: str
  
