name: "homeassistant-acme-sh"
description: "A docker container to renew cert with acme.sh and godaddy"
version: "1.5.0"
slug: "homeassistant-acme-sh"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl:rw
  - acme:rw
options:
  acme_email: ''
  acme_api_key: ''
  acme_api_secret: ''
  acme_dnsapi: ''
  acme_domain: ''
schema:
  acme_email: str
  acme_api_key: password
  acme_api_secret: password
  acme_dnsapi: str
  acme_domain: str
  